### ISSUE TITLE
tars have incorrect mtime in header

### ISSUE THREAD

**Issue by unixlab** [owncloud/TarStreamer#10]
Hi!

I noticed that the tar files generated by owncloud >= 10.3.0 (which bump TarStreamer from 0.1.0 to 0.1.1) do have an incorrect mtime in the tar header:
```
$ tar xf <owncloud-generated-tar>.tar
tar: Archive contains ‘1575293444’ where numeric time_t value expected
tar: Archive contains ‘1575293444’ where numeric time_t value expected
```
As far as I see this is due to a missing conversion from decimal to octal, together with a missing padding.
I assume this got lost with the work done in pr #6.

Cheers
Felix

**Comment by DeepDiver1975** [comment]
https://packagist.org/packages/owncloud/tarstreamer#0.1.2
