### ISSUE TITLE
Release 0.1.2

### ISSUE THREAD

**Issue by VicDeo** [owncloud/TarStreamer#14]
Changelog:
- fixed incorrect mtime in tar header https://github.com/owncloud/TarStreamer/issues/10

**Comment by VicDeo** [comment]
@DeepDiver1975 what steps need to be done for the release?

**Comment by DeepDiver1975** [comment]
tag a release in here - packagist will be updated automatically

**Comment by DeepDiver1975** [comment]
here we go . https://packagist.org/packages/owncloud/tarstreamer#0.1.2
