### ISSUE TITLE
CI is on Travis and not working

### ISSUE THREAD

**Issue by phil-davis** [owncloud/TarStreamer#21]
I suggest that we setup CI on drone for this repo.

**Comment by phil-davis** [comment]
I noticed the problem because no CI has started for #20

**Comment by DeepDiver1975** [comment]
@phil-davis feel free to hook up drone to this repo - THX a lot :pray:

**Comment by phil-davis** [comment]
@DeepDiver1975 I don't have access to the repo settings. Please remove "Travis required" from the settings.

**Comment by phil-davis** [comment]
@DeepDiver1975 
https://drone.owncloud.com/owncloud/TarStreamer/settings

"This Repository is not Active.
Please contact the repository administrator to activate this repository."

Please do whatever to active this repo on drone.

**Comment by DeepDiver1975** [comment]
Done

**Comment by phil-davis** [comment]
@DeepDiver1975 still needs the drone to be enabled please:
https://drone.owncloud.com/owncloud/TarStreamer/settings

**Comment by DeepDiver1975** [comment]
Done

**Comment by DeepDiver1975** [comment]
taken care of - THX @phil-davis
