### ISSUE TITLE
Please register on packagist

### ISSUE THREAD

**Issue by remicollet** [owncloud/TarStreamer#8]
Searching for this extension on packagist:
- https://packagist.org/packages/deepdiver1975/tarstreamer
- sources : here

But, in composer.json

```
   "name": "owncloud/tarstreamer",
```

Which is not found on packagist.

**Comment by remicollet** [comment]
Probably a "replace": "deepdiver1975/tarstreamer" should also be added in composer.json

**Comment by DeepDiver1975** [comment]
here we go - https://packagist.org/packages/owncloud/tarstreamer

**Comment by remicollet** [comment]
Thanks
